version: '3.8'

services:
  web:
    container_name: ime_react_kontejnera
    build:
      context: .
      dockerfile: Dockerfile  
    environment:
      - NODE_ENV=production
    ports:
      - "3000:80"  
    networks:
      - my_network

networks: